// All subsequences, generated by increasing length (index-order combinations).
// Time: O(n * 2^n) output, Space: O(n) recursion.

fn rec(chars: &[char], size: usize, start: usize, idx: &mut Vec<usize>) {
    if idx.len() == size {
        let t: String = idx.iter().map(|&i| chars[i]).collect();
        println!("{}", t);
        return;
    }
    for i in start..chars.len() {
        idx.push(i);
        rec(chars, size, i + 1, idx);
        idx.pop();
    }
}

fn main() {
    let chars: Vec<char> = "xyz".chars().collect();
    for size in 1..=chars.len() {
        let mut idx = Vec::new();
        rec(&chars, size, 0, &mut idx);
    }
}
