// All subsequences, generated by increasing length (index-order combinations).
// Time: O(n * 2^n) output, Space: O(n) recursion.
#include <bits/stdc++.h>
using namespace std;

void gen(const string& s, int size){
    int n = s.size();
    vector<int> idx(size);
    function<void(int,int)> rec = [&](int start, int depth){
        if(depth == size){ string t; for(int x : idx) t += s[x]; cout << t << "\n"; return; }
        for(int i=start;i<n;i++){ idx[depth]=i; rec(i+1, depth+1); }
    };
    rec(0,0);
}

int main(){
    string s = "xyz";
    for(int size=1; size<=(int)s.size(); size++) gen(s, size);
    return 0;
}
