// All subsequences, generated by increasing length (index-order combinations).
// Time: O(n * 2^n) output, Space: O(n) recursion.
public class Solution {
    static void rec(String s, int size, int start, int depth, int[] idx){
        if(depth == size){
            StringBuilder b = new StringBuilder();
            for(int x : idx) b.append(s.charAt(x));
            System.out.println(b);
            return;
        }
        for(int i=start;i<s.length();i++){ idx[depth]=i; rec(s, size, i+1, depth+1, idx); }
    }

    public static void main(String[] args){
        String s = "xyz";
        for(int size=1; size<=s.length(); size++) rec(s, size, 0, 0, new int[size]);
    }
}
