// All subsequences, generated by increasing length (index-order combinations).
// Time: O(n * 2^n) output, Space: O(n) recursion.
function gen(s, size) {
  const idx = new Array(size);
  const out = [];
  (function rec(start, depth) {
    if (depth === size) { out.push(idx.map(i => s[i]).join("")); return; }
    for (let i = start; i < s.length; i++) { idx[depth] = i; rec(i + 1, depth + 1); }
  })(0, 0);
  return out;
}

const s = "xyz";
for (let size = 1; size <= s.length; size++) {
  for (const sub of gen(s, size)) console.log(sub);
}
