// All subsequences, generated by increasing length (index-order combinations).
// Time: O(n * 2^n) output, Space: O(n) recursion.
package main

import "fmt"

func gen(s string, size int) {
	idx := make([]int, size)
	var rec func(start, depth int)
	rec = func(start, depth int) {
		if depth == size {
			b := make([]byte, size)
			for i, x := range idx {
				b[i] = s[x]
			}
			fmt.Println(string(b))
			return
		}
		for i := start; i < len(s); i++ {
			idx[depth] = i
			rec(i+1, depth+1)
		}
	}
	rec(0, 0)
}

func main() {
	s := "xyz"
	for size := 1; size <= len(s); size++ {
		gen(s, size)
	}
}
