# Day 379: All subsequences, generated by increasing length (index-order combinations).
# Time: O(n * 2^n) output, Space: O(n).
from itertools import combinations


def subsequences(s):
    for size in range(1, len(s) + 1):
        for combo in combinations(s, size):
            yield "".join(combo)


if __name__ == "__main__":
    for sub in subsequences("xyz"):
        print(sub)
